### ISSUE TITLE
User parameter is empty when copying receive connector permissions

### ISSUE THREAD

**Issue by Apoc70** [Apoc70/PowerShell-Scripts#2]
An issue with copying receive connector permissions.

Get-ReceiveConnector -Identity ('{0}\{1}' -f $TargetServerName, $sourceRC.Name) -DomainController $DomainController | Add-ADPermission -DomainController $DomainController -User $_.User -Deny:$_.Deny -AccessRights $_.AccessRights -ExtendedRights $_.ExtendedRights

$_.User is empty.

**Comment by robertRuncak** [comment]
Have you fixed a bug with copying receive connector permissions?

**Comment by Apoc70** [comment]
@robertRuncak The current release does not show the empty user issues anymore. At least in the prod environment where I tested this version.
