### ISSUE TITLE
Error with remoteip list

### ISSUE THREAD

**Issue by sc211166** [Apoc70/PowerShell-Scripts#3]
When running the script to copy the receive connector to a new server I got this error message.
Cannot process argument transformation on parameter 'RemoteIPRanges'. Cannot convert value "172.22.0.0/16
172.21.0.0/16" to type "Microsoft.Exchange.Data.MultiValuedProperty`1[Microsoft.Exchange.Data.IPRange]". Error:
"Cannot convert value "172.22.0.0/16" to type "Microsoft.Exchange.Data.IPRange". Error:
"SerializationTypeConverter.DeserializeObject(Microsoft.Exchange.Data.IPRange). Type is not allowed for custom
construction. Deserialization Failed Error: System.Exception: SerializationData is not signed.
   at Microsoft.Exchange.Data.SerializationTypeConverter.VerifySerializationDataAndGetOriginalSerializationData(Byte[]
serializationData, Boolean mustVerify)
   at Microsoft.Exchange.Data.SerializationTypeConverter.DeserializeObject(Object sourceValue, Type destinationType)""
    + CategoryInfo          : InvalidData: (:) [New-ReceiveConnector], ParameterBindin...mationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,New-ReceiveConnector

**Comment by Apoc70** [comment]
The script works with PS serialization signing enabled.
